### ISSUE TITLE
Schema 风格

### ISSUE THREAD

**Issue by linonetwo** [leancloud/leancloud-graphql#2]
看起来你们使用的是 Apollo 风格的  Schema，没有 relay 常见的 viewer， connection 等设计，对吧？

有一些类型前面加个 _ ，这是什么思路呢？

还有权限管理等安全方面你们是怎么做的？

**Comment by HaveF** [comment]
@linonetwo 精子的这个repo, schema只用了纯的graphql，relay那一套感觉好繁琐啊。（自从看了你博客中的那些relay使用经历，relay学都不想学了:joy:）
代码我草草看了一下，权限它还是扔给了原来的api去做，这里只是，把原来api鉴权之后的`X-LC-Session`传给了后面的查询，创建，删除api了

对于用户端来说，还是得使用原来的api来登陆鉴权，然后查询可以使用graphql，也可以使用原来的api，多个入口

我觉得按照apollo的思路，这个repo应该算是connector+model+middleware的结合体，connector就不说了，为了方便使用，把leancloud中的schema取下来 [leancloud-graphql/schema.js at master · leancloud/leancloud-graphql](https://github.com/leancloud/leancloud-graphql/blob/master/schema.js#L44) --- 对应apollo的model，然后把中间件给暴露出去给express使用。

connector+model拆出来可能会更好一些，apollo就也可以用了

**Comment by jysperm** [comment]
>看起来你们使用的是 Apollo 风格的 Schema，没有 relay 常见的 viewer， connection 等设计，对吧？

我主要做后端开发，不是很了解 Relay，后续我可以去了解一下。

>有一些类型前面加个 _ ，这是什么思路呢？

这是因为 LeanCloud 上 `_User` 之类的 Class 本身名字就是下划线开头的，并不是 leancloud-graphql 可以添加的。

>还有权限管理等安全方面你们是怎么做的？

README 中有提到，客户端可以发送 X-LC-Session，leancloud-grpahql 会根据 LeanCloud 现有的 ACL 机制进行鉴权；如果不发的话就相当于是匿名的权限，一般情况下是可以读取和创建，但不能修改（当然这个是可以设置的，关于 LeanCloud 的权限系统可以看 https://leancloud.cn/docs/acl_guide-js.html ）

**Comment by linonetwo** [comment]
感谢分享，这个远程 schema 的实践很棒，我已经推荐给 Apollo 团队看了。
