### ISSUE TITLE
Error in schma type GeoPoint

### ISSUE THREAD

**Issue by theseushu** [leancloud/leancloud-graphql#3]
尝试部署了一下，发现一个error
`Unhandled rejection Error: Product.geopoint field type must be Output Type but got: undefined.
ERROR web1 16:48:48     at invariant (/home/leanengine/app/node_modules/graphql/jsutils/invariant.js:19:11)
ERROR web1 16:48:48     at /home/leanengine/app/node_modules/graphql/type/definition.js:326:29
ERROR web1 16:48:48     at defineFieldMap (/home/leanengine/app/node_modules/graphql/type/definition.js:318:14)
ERROR web1 16:48:48     at GraphQLObjectType.getFields (/home/leanengine/app/node_modules/graphql/type/definition.js:276:44)
ERROR web1 16:48:48     at /home/leanengine/app/node_modules/graphql/type/schema.js:207:27
ERROR web1 16:48:48     at typeMapReducer (/home/leanengine/app/node_modules/graphql/type/schema.js:219:7)
ERROR web1 16:48:48     at typeMapReducer (/home/leanengine/app/node_modules/graphql/type/schema.js:187:12)
ERROR web1 16:48:48     at /home/leanengine/app/node_modules/graphql/type/schema.js:217:22
ERROR web1 16:48:48     at Array.forEach (native)
ERROR web1 16:48:48     at typeMapReducer (/home/leanengine/app/node_modules/graphql/type/schema.js:219:7)
ERROR web1 16:48:48     at /home/leanengine/app/node_modules/graphql/type/schema.js:217:22
ERROR web1 16:48:48     at /home/leanengine/app/node_modules/graphql/type/schema.js:208:29
ERROR web1 16:48:48     at typeMapReducer (/home/leanengine/app/node_modules/graphql/type/schema.js:219:7)
ERROR web1 16:48:48     at /home/leanengine/app/node_modules/graphql/type/schema.js:217:22
ERROR web1 16:48:48     at /home/leanengine/app/node_modules/graphql/type/schema.js:208:29`

似乎geopoint的shema有点问题需要特殊处理一下？

**Comment by jysperm** [comment]
确实没有考虑到 GeoPoint ...

**Comment by jysperm** [comment]
我发布了 0.3.0 这个版本解决这个问题，可以试一下
